# Generated by Django 5.2.11 on 2026-03-10 00:00

import django.db.models.deletion
from django.db import migrations, models


def seed_roles(apps, schema_editor):
    Role = apps.get_model("app", "Role")
    Customer = apps.get_model("app", "Customer")

    customer_role, _ = Role.objects.get_or_create(name="customer")
    Role.objects.get_or_create(name="staff")

    Customer.objects.filter(role__isnull=True).update(role=customer_role)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("staff", "Staff"), ("customer", "Customer")],
                        max_length=32,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customer",
            name="role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customers",
                to="app.role",
            ),
        ),
        migrations.RunPython(seed_roles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="customer",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customers",
                to="app.role",
            ),
        ),
    ]
