# Generated by Django 5.2.10 on 2026-03-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('shipping_method', models.CharField(max_length=50)),
                ('shipping_address', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('created', 'Created'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='created', max_length=30)),
                ('payment_status', models.CharField(default='pending', max_length=30)),
                ('shipping_status', models.CharField(default='pending', max_length=30)),
                ('payment_id', models.IntegerField(blank=True, null=True)),
                ('shipping_id', models.IntegerField(blank=True, null=True)),
                ('items', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
