# Generated by Django 5.2.11 on 2026-03-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="promotion_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
